-- ==============================================================
-- File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.2
-- Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
-- 
-- ==============================================================

library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity DNN_HiddenLayer_3_bias_rom is 
    generic(
             dwidth     : integer := 32; 
             awidth     : integer := 5; 
             mem_size    : integer := 32
    ); 
    port (
          addr0      : in std_logic_vector(awidth-1 downto 0); 
          ce0       : in std_logic; 
          q0         : out std_logic_vector(dwidth-1 downto 0);
          clk       : in std_logic
    ); 
end entity; 


architecture rtl of DNN_HiddenLayer_3_bias_rom is 

signal addr0_tmp : std_logic_vector(awidth-1 downto 0); 
type mem_array is array (0 to mem_size-1) of std_logic_vector (dwidth-1 downto 0); 
signal mem : mem_array := (
    0 => "11000001110001100100111000000010", 
    1 => "11000000111011011110000101000000", 
    2 => "11000001010010110010110111101100", 
    3 => "11000001000011101111110010110100", 
    4 => "11000000111001110111010001010100", 
    5 => "11000001100010000110110101101001", 
    6 => "11000001000111010011011111001010", 
    7 => "01000000101101010001111010000010", 
    8 => "10111111110110000111011001110000", 
    9 => "11000000110011100001010011010010", 
    10 => "11000000010111111010010010100100", 
    11 => "11000001100000011001110110110100", 
    12 => "11000001110000010011001011110100", 
    13 => "11000001001101101110010101100100", 
    14 => "11000000100000010001110010110110", 
    15 => "10111111011010111100111111111000", 
    16 => "11000001001011011000011110011111", 
    17 => "11000000000111001011001001100010", 
    18 => "11000000111001101011110000111111", 
    19 => "11000001000100111000111001111001", 
    20 => "11000001100101010010111011100101", 
    21 => "11000000111111011001011101000011", 
    22 => "11000000100010000010101101000001", 
    23 => "11000000100010110010010111001101", 
    24 => "10111111000010000110000011000001", 
    25 => "11000001001011011100001001000101", 
    26 => "11000001101001001100100000010000", 
    27 => "11000001010110100111010010001111", 
    28 => "11000000111000001110000001011001", 
    29 => "11000001010111101110010101110010", 
    30 => "11000001000011000010010011111001", 
    31 => "01000000110000010001010000010000" );


attribute EQUIVALENT_REGISTER_REMOVAL : string;
begin 


memory_access_guard_0: process (addr0) 
begin
      addr0_tmp <= addr0;
--synthesis translate_off
      if (CONV_INTEGER(addr0) > mem_size-1) then
           addr0_tmp <= (others => '0');
      else 
           addr0_tmp <= addr0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
        if (ce0 = '1') then 
            q0 <= mem(CONV_INTEGER(addr0_tmp)); 
        end if;
    end if;
end process;

end rtl;


Library IEEE;
use IEEE.std_logic_1164.all;

entity DNN_HiddenLayer_3_bias is
    generic (
        DataWidth : INTEGER := 32;
        AddressRange : INTEGER := 32;
        AddressWidth : INTEGER := 5);
    port (
        reset : IN STD_LOGIC;
        clk : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0));
end entity;

architecture arch of DNN_HiddenLayer_3_bias is
    component DNN_HiddenLayer_3_bias_rom is
        port (
            clk : IN STD_LOGIC;
            addr0 : IN STD_LOGIC_VECTOR;
            ce0 : IN STD_LOGIC;
            q0 : OUT STD_LOGIC_VECTOR);
    end component;



begin
    DNN_HiddenLayer_3_bias_rom_U :  component DNN_HiddenLayer_3_bias_rom
    port map (
        clk => clk,
        addr0 => address0,
        ce0 => ce0,
        q0 => q0);

end architecture;


